repos:

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt         # Uses prebuilt upstream executable
      # Alternatively, you can use one of the following:
      # - id: shfmt-src   # Builds from source (requires Go)
      # - id: shfmt-docker  # Uses Docker (requires Docker installed)


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@3.2.5']
        files: \.(md|html|css|js)$

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-executables-have-shebangs

  - repo: local
    hooks:
      - id: batlint
        name: Lint BAT files
        entry: batlint
        language: system
        files: \.bat$
